import Foundation

// AUTO-GENERATED from the T("…") literals in Sources/Views. Sent to the server's
// ui_strings action so each chrome string is registered + translated (on-demand,
// then cached) into the viewer's language. Regenerate after adding new T() strings:
//   grep -rhoE 'T\("([^"\\]|\\.)*"\)' Sources/Views | sed -E 's/^T\("//; s/"\)$//' | sort -u
enum UIStringCatalog {
    static let all: [String] = [
        "@mention Derek or DeepSeek in any thread, comment, chat line, or a 1:1 DM.",
        "A clearer subject helps people find and answer your post.",
        "AI assistants",
        "About you",
        "Account",
        "Add a comment",
        "Add or remove people; archived conversations return when there’s new activity.",
        "Add people",
        "Admin",
        "All",
        "All forums",
        "Appearance",
        "Archive",
        "Ask Derek about “{q}”",
        "Ask Derek for an AI answer drawn from the whole forum.",
        "Attach images by picking from your library; tap an image to view it full-size.",
        "Basecamp",
        "Before you post",
        "Best matches",
        "Boosts",
        "CHAT",
        "COMMENT",
        "Cancel",
        "Category",
        "Change photo",
        "Chat",
        "Chat Room",
        "Chat lines and direct messages don’t have reactions.",
        "Choose how far back — since your last visit or a number of days.",
        "Choose which notifications you get as pop-ups or email.",
        "City",
        "Clear filter",
        "Clearer subject?",
        "Close account",
        "Close your account?",
        "Closed",
        "Coffee & food",
        "Comment",
        "Comments",
        "Content and the interface appear in your language. Interface translations arrive as they’re added on the server.",
        "Content is shown in your language automatically.",
        "Copy link",
        "Couldn’t load profile",
        "Couldn’t post",
        "Couldn’t read that photo. Try a different one.",
        "Couldn’t send",
        "Couldn’t update your photo",
        "Countries",
        "Country",
        "DM",
        "DMs",
        "Daily",
        "Dark",
        "Delete",
        "Delete this comment?",
        "Delete this post?",
        "Derek is thinking…",
        "Derek may already have an answer",
        "Derek says",
        "Direct Messages",
        "Direct messages",
        "Discover regional & roaster forums.",
        "Display name",
        "Done",
        "Drafts are kept per thread, and ⌘↵ sends.",
        "Each forum holds threads. Tap a forum to see its threads, newest activity first.",
        "Edit",
        "Edit comment",
        "Edit message",
        "Email",
        "Email me a sample",
        "Email me summaries",
        "Experts only",
        "Failed",
        "Filter",
        "Filter by Popular, I posted, I commented, or I’m mentioned.",
        "Filter by Threads, Comments, Chat or DMs.",
        "Filter by name",
        "Filter by type and forum, sort by relevance or newest, and keep only the best matches.",
        "Filter off",
        "Filter on",
        "Find forums",
        "Find people",
        "Find someone",
        "Find threads, comments, chat, DMs and people.",
        "Forums",
        "Frequency",
        "Generating…",
        "Gestures",
        "Get summaries by email daily, weekly, or monthly, and email yourself a sample.",
        "Help",
        "Hide",
        "I commented",
        "I posted",
        "I'm mentioned",
        "Image unavailable",
        "Include",
        "Invite",
        "Join",
        "Keep it here",
        "Keep mine",
        "Language",
        "Languages",
        "Leave",
        "Let me reconsider",
        "Light",
        "Link to this",
        "Linked",
        "Live",
        "Live community chat for Decent espresso owners.",
        "Location",
        "Manage muted people, your Basecamp link, appearance (light/dark), and closing your account.",
        "Manage sources & email a sample",
        "Mark all read",
        "Mark as",
        "Mentions",
        "Message",
        "Message the room… (rich text, @mention)",
        "Messages",
        "Messages: {t}",
        "Messages: {t} · {r} in the last 24h",
        "Monthly",
        "Move it",
        "Move to its own thread?",
        "Mute",
        "Mute someone to hide their messages, comments, chat and DMs, and stop their notifications.",
        "Muted people",
        "My settings",
        "Name this filter…",
        "New group message",
        "New mentions, replies and messages will appear here.",
        "New message",
        "New since your last visit",
        "Newest",
        "No category",
        "No conversations with a participant matching your filter.",
        "No matches",
        "No messages yet",
        "No regional or roaster forums are available yet.",
        "No threads yet",
        "Not linked",
        "Nothing to discover",
        "Notifications",
        "Notifications, {n} unread",
        "Now using",
        "OK",
        "Objects",
        "Open anyone’s card to see their activity, machine, and a Message button.",
        "Opens a secure browser. Your password is never entered in the app.",
        "Other",
        "People",
        "People & privacy",
        "Pin",
        "Popular",
        "Popup",
        "Popups appear in-app and as push. Email for mentions/replies is paused in favour of summaries.",
        "Post",
        "Post anyway",
        "Post rich text and @mention people or the AI assistants.",
        "Posts get auto-categorised, and problem-like posts may be moved to Problems.",
        "Preview",
        "Preview my digest",
        "Private conversations.",
        "Private one-to-one or group conversations, shown as chat bubbles.",
        "Profile",
        "Quote & reply",
        "Quote & reply keeps the original author’s attribution.",
        "React to any message or comment with an emoji. Tap a reaction to add or remove yours.",
        "Reactions",
        "Reason",
        "Regional forums",
        "Relevance",
        "Remove",
        "Replies to my threads",
        "Reply",
        "Report",
        "Report someone to the moderators.",
        "Report {name}?",
        "Results",
        "Rich text with colour and highlight, plus @mentions of people (and bots).",
        "Roaster forums",
        "SUGGESTED",
        "Sample sent",
        "Save",
        "Save location",
        "Save profile",
        "Save summary settings",
        "Saved filters",
        "Search",
        "Search by name; pick one or more.",
        "Search countries…",
        "Search dcamp",
        "Search emoji",
        "Search help",
        "Search people",
        "Search people by name.",
        "Search threads, comments, chat, your DMs, and people.",
        "Select a conversation",
        "Send",
        "Send me a summary",
        "Server",
        "Set your name, about, picture, and location (and whether it shows on your card).",
        "Show",
        "Show in sidebar",
        "Show my city & country on my profile",
        "Show translation",
        "Sign in with Decent",
        "Sign in with your existing Decent support account.",
        "Sign out",
        "Signing in…",
        "Smileys",
        "Solved",
        "Someone",
        "Something went wrong",
        "Sort",
        "Sort by relevance or newest; “Best matches” hides weak hits.",
        "Start",
        "Start a private conversation.",
        "Subject",
        "Summaries",
        "Summaries by email",
        "Summarize",
        "Summarizing…",
        "Switch server?",
        "Switch to Live (decentespresso.com)",
        "Switch to Test (localhost:8000)",
        "Switching signs you out; you'll sign in again on the selected server.",
        "Symbols",
        "System",
        "THREAD",
        "Tap “Show original text” on any post to see what was originally written.",
        "Tap ✨ Summarize on the home, a forum, a thread, or chat for an AI digest.",
        "Test",
        "The Chat Room is a live, flat conversation for Decent owners.",
        "The Problems board tracks issues with an Unsolved / Solved / Closed status.",
        "The home summary highlights where you were mentioned.",
        "Theme",
        "They draw on the whole forum and reply in your language; answers stream in.",
        "This alerts the moderators.",
        "This can’t be undone.",
        "This comment looks like it’s about something else. Move it to its own thread?",
        "This removes the whole thread. This can’t be undone.",
        "Thread",
        "Threads",
        "Threads I follow",
        "Tips",
        "Translated · Show original",
        "Type Markdown as you go: # headings, - lists, > quotes, **bold**, *italic*, ``` code.",
        "Type two or more letters to search.",
        "US",
        "Unmute",
        "Unpin",
        "Unread counts show which conversations have new messages.",
        "Unsolved",
        "Untitled",
        "Uploading image…",
        "Uploading…",
        "Use suggested subject",
        "Use “Link to this” to copy a link to any chat line.",
        "Weekly",
        "Welcome to the Decent Diaspora",
        "When you start a question-like post, Derek may already have an answer to show you.",
        "Write a comment… (rich text, @mention)",
        "Write a direct message… (rich text, @mention)",
        "Write something before posting.",
        "Writing posts",
        "YOUR SUBJECT",
        "You have read-only access — chat is for current Decent machine owners.",
        "You have read-only access — posting is for current Decent machine owners.",
        "You were mentioned",
        "You'll be signed out and need to sign in again on the selected server.",
        "Your account",
        "Your posts stay, but you’re removed from search, @mention and the member list. Logging in again reopens it.",
        "You’re all caught up",
        "You’re signed up for daily summaries.",
        "You’re signed up for monthly summaries.",
        "You’re signed up for weekly summaries.",
        "commented on a thread you follow",
        "dcamp",
        "dcamp id",
        "mentioned you",
        "moved your post to its own thread",
        "new activity",
        "not translated",
        "past {n} day",
        "past {n} days",
        "replied to your thread",
        "sent you a message",
        "{n} comment",
        "{n} comments",
        "“Experts only” narrows people to recognised experts.",
    ]
}
