import Foundation

// AUTO-GENERATED from the T("…") literals in Sources/Views. Sent to the server's
// ui_strings action so each chrome string is registered + translated (on-demand,
// then cached) into the viewer's language. Regenerate after adding new T() strings:
//   grep -rhoE 'T\("([^"\\]|\\.)*"\)' Sources/Views | sed -E 's/^T\("//; s/"\)$//' | sort -u
enum UIStringCatalog {
    static let all: [String] = [
        "A clearer subject helps people find and answer your post.",
        "About you",
        "Account",
        "Add a comment",
        "Add people",
        "Admin",
        "Appearance",
        "Archive",
        "Ask Derek for an AI answer drawn from the whole forum.",
        "Basecamp",
        "Before you post",
        "Cancel",
        "Category",
        "Chat Room",
        "City",
        "Clear",
        "Clearer subject?",
        "Close account",
        "Close your account?",
        "Closed",
        "Comments",
        "Content and the interface appear in your language. Interface translations arrive as they’re added on the server.",
        "Copy link",
        "Couldn’t load profile",
        "Couldn’t post",
        "Country",
        "Daily",
        "Delete",
        "Delete this comment?",
        "Delete this post?",
        "Derek may already have an answer",
        "Derek says",
        "Direct Messages",
        "Display name",
        "Done",
        "Edit",
        "Email",
        "Email me summaries",
        "Experts only",
        "Filter by Threads, Comments, Chat or DMs.",
        "Find forums",
        "Find people",
        "Find someone",
        "Find threads, comments, chat, DMs and people.",
        "Forums",
        "Frequency",
        "Generating…",
        "Help",
        "Highlight",
        "Include",
        "Join",
        "Keep it here",
        "Keep mine",
        "Language",
        "Leave",
        "Let me reconsider",
        "Link to this",
        "Location",
        "Manage sources & email a sample",
        "Mark all read",
        "Mark as",
        "Message",
        "Messages",
        "Monthly",
        "Move it",
        "Move to its own thread?",
        "Muted people",
        "My settings",
        "New group message",
        "New mentions, replies and messages will appear here.",
        "New message",
        "New since your last visit",
        "Newest",
        "No category",
        "No messages yet",
        "No regional or roaster forums are available yet.",
        "No threads yet",
        "Nothing to discover",
        "Notifications",
        "OK",
        "Opens a secure browser. Your password is never entered in the app.",
        "Pin",
        "Popup",
        "Popups appear in-app and as push. Email for mentions/replies is paused in favour of summaries.",
        "Post",
        "Post anyway",
        "Preview",
        "Preview my digest",
        "Profile",
        "Quote & reply",
        "React",
        "Reason",
        "Relevance",
        "Remove",
        "Report",
        "SUGGESTED",
        "Save location",
        "Save profile",
        "Save summary settings",
        "Search",
        "Search by name; pick one or more.",
        "Search dcamp",
        "Search help",
        "Search people",
        "Search people by name.",
        "Select a conversation",
        "Send",
        "Send me a summary",
        "Show in sidebar",
        "Show my city & country on my profile",
        "Sign in with your existing Decent support account.",
        "Sign out",
        "Solved",
        "Something went wrong",
        "Sort",
        "Sort by relevance or newest; “Best matches” hides weak hits.",
        "Start",
        "Start a private conversation.",
        "Subject",
        "Summaries by email",
        "Summarizing…",
        "Text colour",
        "Theme",
        "This alerts the moderators.",
        "This can’t be undone.",
        "This comment looks like it’s about something else. Move it to its own thread?",
        "This removes the whole thread. This can’t be undone.",
        "Threads",
        "Tips",
        "Type two or more letters to search.",
        "US",
        "Unmute",
        "Unpin",
        "Unsolved",
        "Uploading image…",
        "Use suggested subject",
        "Weekly",
        "Welcome to the Decent Diaspora",
        "YOUR SUBJECT",
        "You have read-only access — chat is for current Decent machine owners.",
        "You have read-only access — posting is for current Decent machine owners.",
        "You were mentioned",
        "Your posts stay, but you’re removed from search, @mention and the member list. Logging in again reopens it.",
        "You’re all caught up",
        "dcamp",
        "not translated",
        "“Experts only” narrows people to recognised experts.",
    ]
}
